name: build

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  yarn-audit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - run: yarn audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - run: yarn install --immutable

      - name: eslint
        run: yarn lint:js

      - name: markdownlint
        run: yarn lint:md

      - name: prettier
        run: yarn format:ci
